blank_issues_enabled: false
contact_links:
  - name: Suggest a new feature
    about: Feature request, enhancement idea, new functionality? Open a discussion!
    url: https://github.com/kedro-org/kedro/discussions/new?category=idea
  - name: Ask for help
    about: Come chat with the community in Slack!
    url: https://slack.kedro.org/
